/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FormField from "./FormField";

function FormsWrapper() {
  return (
    <section className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-3.5 items-end self-end p-12 text-4xl font-bold tracking-normal leading-10 text-orange-500 max-md:px-5">
        <div className="opacity-[var(--sds-size-stroke-border)] w-[154px]">
          <span className="text-gray-800">i</span>
          <span className="text-orange-500">Prestasi</span>
        </div>
      </div>
      <div className="flex flex-col justify-center px-14 py-20 mt-36 max-w-full bg-white rounded-3xl border-solid border-[3px] border-zinc-300 min-h-[531px] w-[598px] max-md:px-5 max-md:mt-10">
        <div className="flex flex-col w-full max-md:max-w-full">
          <div className="text-2xl font-medium tracking-normal leading-8 text-gray-800 opacity-[var(--sds-size-stroke-border)] max-md:max-w-full">
            Selamat Datang, Fikers!
          </div>
          <FormField
            id="email"
            label="Email"
            type="email"
            value="ava.wright@gmail.com"
          />
          <FormField
            id="password"
            label="Kata Sandi"
            type="password"
            value="********"
          />
        </div>
        <button className="flex overflow-hidden gap-2 justify-center items-center px-6 py-3 mt-12 w-full text-base font-medium tracking-normal leading-6 text-white whitespace-nowrap bg-orange-500 rounded-lg max-md:px-5 max-md:mt-10 max-md:max-w-full">
          Masuk
        </button>
      </div>
    </section>
  );
}

export default FormsWrapper;
